# Use official Node.js image
FROM node:22-slim

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package.json /app

# Install dependencies
RUN npm install

# Copy all backend source code
COPY . /app

# Command to run your backend
CMD ["node", "server.js"]
