name: Build and Push to ACR

on:
    workflow_dispatch:

env:
  ACR_NAME: mernappacr               # Replace with your actual ACR name
  IMAGE_FRONTEND: frontend:latest
  IMAGE_BACKEND: backend:latest

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v3
    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Azure ACR login
      uses: azure/docker-login@v1
      with:
        login-server: ${{ env.ACR_NAME }}.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Push mongo expres
      run: |
        docker pull mongo-express                # Get official image
        docker tag mongo-express $ACR_NAME.azurecr.io/mongo-express:latest
        docker push $ACR_NAME.azurecr.io/mongo-express:latest
    
    - name: Push mongodb
      run: |
        docker pull mongo                # Get official image
        docker tag mongo $ACR_NAME.azurecr.io/mongo:latest
        docker push $ACR_NAME.azurecr.io/mongo:latest
        
    - name: Create Mongo container
      run: |
          az container create \
            --resource-group mern-app-rg \
            --name mongodb \
            --image ${{ env.ACR_NAME }}.azurecr.io/mongo:latest \
            --registry-login-server ${{ env.ACR_NAME }}.azurecr.io \
            --registry-username ${{ secrets.ACR_USERNAME }} \
            --registry-password ${{ secrets.ACR_PASSWORD }} \
            --cpu 1 \
            --memory 1 \
            --ports 8081           
            
    - name: Build and push frontend
      run: |
        docker build -t $ACR_NAME.azurecr.io/$IMAGE_FRONTEND ./frontend
        docker push $ACR_NAME.azurecr.io/$IMAGE_FRONTEND

    - name: Build and push backend
      run: |
        docker build -t $ACR_NAME.azurecr.io/$IMAGE_BACKEND ./backend
        docker push $ACR_NAME.azurecr.io/$IMAGE_BACKEND
